app:
  config:
    argument: basement
spring:
  profiles:
    active: overprod
    group:
      prodover:
        - prod
        - override
      overprod:
        - override
        - prod
  config:
    import: file:./import.yml